# Generated by Django 5.1.6 on 2025-03-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('periority', models.IntegerField(default=1)),
                ('is_done', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'todos',
            },
        ),
    ]
